### ISSUE TITLE
Is there any way to optimize GPU memory?

### ISSUE THREAD

**Issue by dirtycomputer** [tunakasif/torch-frft#12]
GPU memory consume more during training my network instead of torch.fft

**Comment by tunakasif** [comment]
As answered in #11 and provided in `README.md`, the implementation is based on the given papers. The asymptotic time-complexity of `frft()` is $\mathcal{O}(N\log N)$ where $N$ is the time-bandwidth product; please refer to the papers. On the other hand, for a discrete signal $\boldsymbol{x}\in\mathbb{R}^M$, since the `dfrft()` contains a complete matrix multiplication at the last step, the time-complexity is $\mathcal{O}(M^3)$. Furthermore, note that these are asymptotic complexities; we are doing so much in `frft()` compared to `fft()`, e.g., chirp convolution. For small $M$, `dfrft()` works faster than `frft()`, only with large $M$, you see the difference. Finally, all the mentioned fractional transforms are expected to work slower than their ordinary counterparts.

There are a few approaches that claim efficient implementation of FRFT, e.g., [An Efficient Fractional Fourier Transform Approach for Digital Image Watermarking](https://www.researchgate.net/publication/263747906_An_Efficient_Fractional_Fourier_Transform_Approach_for_Digital_Image_Watermarking), [An Efficient FPGA-based Implementation of Fractional Fourier Transform Algorithm](https://www.doi.org/10.1007/s11265-009-0401-0) (and its so-called [MATLAB implementation](https://nalag.cs.kuleuven.be/research/software/FRFT/frft2.m)). However, we are using the original source code of the mentioned papers provided by their authors for reliability and correctness. You are welcome to experiment with other approaches. If you can implement a more efficient method resulting in the correct output, then I would be happy to review your pull request, but other than that, it is not planned.

**Comment by dirtycomputer** [comment]
![image](https://github.com/tunakasif/torch-frft/assets/48406770/beb2d936-6106-445a-b8b9-72a2fccaccaa)
If the input is real number only(eg: images), is there anything similar to torch.fft.rfft()?

**Comment by tunakasif** [comment]
## FT Case

For a Fourier pair $x(t)\leftrightarrow X(f)$, with conjugation you get $x^\ast(t)\leftrightarrow X^\ast(-f)$. If the signal $x(t)$ is real, i.e., $x(t) = x^\ast(t)$, then we have $X(f) = X^\ast(-f)$, or equivalently, $X(-f) = X^\ast(f)$. Therefore, you can calculate the negative index values directly from their positive counterparts, which is also exploited by `rfft()`.

## FRFT Case

For a fractional Fourier pair $x(t)\leftrightarrow X_a(u)$, with conjugation you get $x^\ast(t)\leftrightarrow X_{-a}^\ast(u)$. If the signal is real, then you have $X_a(u) = X_{-a}^\ast(u)$. Note that the negation is not applied to the index but to the order. Hence, in general, you **do not** have a direct relationship between the signal's left- and right-hand sides as in the ordinary FT. If you can find a direct relationship between $X_a(u)$ and $X_a(-u)$, then we can implement something like `rfft()`.
