### ISSUE TITLE
inverse frft implementation

### ISSUE THREAD

**Issue by kravrolens** [tunakasif/torch-frft#13]
Hi, Thanks for your elegant code. 

How do I implement the inverse Fourier transform in the fractional domain?

I look forward to your reply, THANKS!

**Comment by kravrolens** [comment]
I find the idfrft function, Thank you!!

**Comment by tunakasif** [comment]
> Hi, Thanks for your elegant code.

Thank you for your kind words.

> How do I implement the inverse Fourier transform in the fractional domain?

Both FRFT and DFRFT modules have inverse functions as [`ifrft()`](https://github.com/tunakasif/torch-frft/blob/5ec81829eb41a3444898ae186e97cd019f3269da/torch_frft/frft_module.py#L9-L10) and [`idfrft()`](https://github.com/tunakasif/torch-frft/blob/5ec81829eb41a3444898ae186e97cd019f3269da/torch_frft/dfrft_module.py#L6-L7), respectively. However, remember that these functions are just basic wrappers due to the properties of the fractional Fourier transform. For a forward transform with order $a$, $\mathcal{F}^a\\{x\\}$, the inverse transform is $\mathcal{F}^{-a}\\{x\\}$. You can refer to the sources and papers in the README. Therefore, we have the following:

```python
import torch
from torch_frft.frft_module import frft, ifrft

N = 128
a = 0.5
X = torch.rand(N, N)
Y = frft(X, a)

X1 = ifrft(X, a)
X2 = frft(X, -a)
assert torch.allclose(X1, X2)
```

You can do the same for `dfrft()` and `idfrft()`.

**Comment by kravrolens** [comment]
I see, thank you for your explanation !!!
