### ISSUE TITLE
dfrft(x_data, alpha).abs()，What does that mean?

### ISSUE THREAD

**Issue by JiacLuo** [tunakasif/torch-frft#15]
### Question：
Hi, Dear Author.
        After doing some experimentation with your code, it feels very interesting. When I try to write the following code: ` dfrft(x_data, alpha).abs()` . **I wonder what that means? Is this similar to the amplitude in FFT?**
        Since I don't know much about the signal processing field, I kindly ask you to tell me why this happens. Looking forward to your answer very much！

Your fans.

**Comment by tunakasif** [comment]
First, assuming `x_data` is a `torch.Tensor` and `alpha` is a `float`, the `dfrft(x_data, alpha)` returns the discrete fractional Fourier transform (DFRFT) of the vectors along the last dimension of the tensor since the function has default `dim=-1`. The result is also `torch.Tensor` and has the same dimensionality as `x_data`.

Second, similar to DFT (FFT), the DFRFT generally returns complex valued results. Taking `.abs()` of the resulting DFRFT results in absolute magnitudes (or amplitudes in your words). Since most activation functions do not accept `ComplexDouble`, especially in machine learning applications, such as training the optimal transform order, it needs some real conversion. Taking the absolute value, real part, imaginary part, or applying operations to real and imaginary parts jointly can be some other approaches. In signal processing, taking the magnitude is usually more meaningful than just the real part, but each may provide better results.

**Comment by JiacLuo** [comment]
Thank you very much for your detailed answer!
